theme: jekyll-theme-minimal
title: Finlay Scheib's Homepage
subtitle: MSc Computational Applied Mathematics @ Uni of Edinburgh
description: Oops! You must've gotten lost. Take a look at my mediocre projects whilst you are here...
email: s2190468@ed.ac.uk
